typography_spectrum: 0.584327589487657
color:
  brandStrength: 0.31673299334943295
  lightness: 0.7428770526312292
  saturation: 0.10798054444603622
  rhythmicContrast: 0.9249672829173505
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
layout_spectrum: 0.09415270551107824
author:
  name: Melissa Barge
  email: sb1295570@aol.com
  url: www.facebook.com/sweetsmarts.com
logo: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com/cbd2bc31-4346-40cb-91da-60b9aea9f03b.jpg'
name: Sweet Smarts
title: Specialty Cakes and Deserts
